# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0415c0e5ecddc15417c15fb3e1a70c5eaddfa0051749e891bdd4b17fb940bb81b7c5ef2f9b58931d2b4d747b9a8edc1715eb0f5605f7673ebe49124dbe7a9b52

test:
  secret_key_base: 8ecb5c2a33bb6d5524bd95145529dd84af9980e8b8cda0ab69095fc9fa4767bff5db84d0d53c66873bfe02f34d3b877d6077ca25345ad840970e323091bd35b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
